---
# tasks file for hosts

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'FreeBSD'

- include_tasks: hostname.yml
- include_tasks: hosts.yml
